### ISSUE TITLE
Refactor data collection and generation process

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#15]
# Description

We have to clean up this junkyard. The [README](https://github.com/okfn/data-quality-uk-25k-spend) on master describes the current flow. The [README](https://github.com/okfn/data-quality-uk-25k-spend/tree/feature/refactor) on the `feature/refactor` branch describes what we want to get to.

The basic thing is that everything to do with building the actual data quality assessment database should be controlled via the [Data Quality CLI](https://github.com/okfn/data-quality-cli), so all the hacks added here for that need to be streamlined into post-pipeline and post-batch hooks there (abstracted into [`Tasks`](https://github.com/okfn/data-quality-cli/blob/master/dq/tasks.py) in that codebase).
# Tasks
- [x] Refer to the [OKI coding standards](https://github.com/okfn/coding-standards) and the [example codebase](https://github.com/okfn/oki-py) for Python style
- [x] Update  the new README to reflect this flow
  - [x] An ID data script, which builds publishers and sources lists
    - [x]  Exclude HTML pages from sources. 
    - [x]  Add functionality for configurable sleep time between pipelines in GoodTables 
    - [x]  Handle HTTP errors and compressed formats in the GoodTables 
    - [x]  Remove `preprocess_sources` script. 
    - [x]  Fetch the cached files as a post-processing task in data-quality-cli 
    - [x]  Remove the `fetch_sources` script. 
    - [x]  After  GoodTables will cover scoring bad things with 0, remove `make_results` script. 
    - [x]  Transform `make_performance` script into a `dq run` task.  
    - [x]  Try again to make `id_data` script compatible with python 2.7 or open another issue 
- [x] Fix the scripts that identify assessable data, and further _manually_ curate the identified data (if it helps streamline the scripts) so that we _only_ assess the relevant publishers, and _only_ on their 25k data (not other documents of spend data)
### Specific notes on data identification
- See [this code](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/scripts/get_data.py#L288) grabs all sorts of fiscal files, not just 25k. we **only** what 25k data.
- See the attached .ods file which was provided by @jacattell as a list of _relevant_ ministerial departments to assess for data quality on 25k publication. Ensure that we do not have publishers (+sources of) that are not on this list - the ones marked in yellow are the ones we have that should not be there according to @jacattell
#### A point about discoverability of data
- It looks like gov.uk is listing datasets that have not been pushed to data.gov.uk. Again, James provided an example query (https://www.gov.uk/government/publications?keywords=spend&publication_filter_option=transparency-data&topics%5B%5D=all&departments%5B%5D=all&official_document_status=all&world_locations%5B%5D=all&from_date=&to_date=). As far as I know, we are _supposed_ to be assessing data.gov.uk, being the data portal of the UK govt., so I'm not 100% sure we should look for data on this location too. @davidread do you have any opinion on that?

[ministerial-departments.ods.zip](https://github.com/okfn/data-quality-uk-25k-spend/files/164742/ministerial-departments.ods.zip)

**Comment by jacattell** [comment]
@pwalsh I've just alerted colleagues in the Cabinet Office Government Digital Service (GDS) to some of the issues. The former Cabinet Office Transparency Team (data.gov.uk owners) joined GDS a few months ago. Personally, I'd love to see GOV.UK and data.gov.uk merge (I naively [blogged about this](https://jacattell.wordpress.com/2012/09/06/hello-world/) 4 years ago)

**Comment by pwalsh** [comment]
Thanks @jacattell

**Comment by pwalsh** [comment]
FIXED :)

**Comment by pwalsh** [comment]
@georgiana-b great work done here!
